Processing test77...
  Caught exception importing module test77:
    File "test_input/test77.py", line 8
      raise MyError("FOO!")

Warnings...

test77:1: NOT PROCESSED UNABLE TO IMPORT
